name: Protected envs and stages

on:
  push:
    branches:
      - master


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: sleep 5

      - name: Finish building
        run: echo "Build completed successfully"
  deployment:
    runs-on: ubuntu-latest
    needs: build-and-push
    strategy:
      max-parallel: 1
      matrix:
        environment: [dev, qa, prod]
    environment: 
      name: ${{ matrix.environment }}
    steps:
      - name: deploy
        run: sleep 5

  # Chain the next job to the previous one and make it deploy
  # to different environments with manual approvals