name: E5

on:
  push:
    branches:
      - master
  schedule: 
    - cron: '*/1 * * * *'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        id: Repeater
        with:
          in-var: TesT
      - run: echo output "$output_var"
        shell: bash
        if: ${{ steps.echo-message.outputs.out_var == 'TesT' }}
        env:
          output_var: ${{ steps.echo-message.outputs.out_var }}
      - run: echo output "$output_var"
        shell: bash
        env:
          output_var: ${{ steps.echo-message.outputs.out_var }}

