name: E5

on:
  schedule: 
    - cron: '*/1 * * * *'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: ./ # Uses an action in the root directory
        id: repeater
        with:
          in-var: Eren


