name: E5

on:
  push:
    branches:
      - master
  schedule: 
    - cron: '*/1 * * * *'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4
      - uses: ./.github/actions # Uses an action in the root directory
        id: repeater
        with:
          in-var: Eren


