name: E5

on:
  push:
    branches:
      - master
  schedule: 
    - cron: '*/1 * * * *'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4
      - name: repeater
        uses: ./ # Uses an action in the root directory
        id: Repeater
        with:
          in-var: TesT
      - run: echo output ${{ steps.repeater.outputs.out_var }}
        shell: bash
        if: ${{ steps.repeater.outputs.out_var == 'TesT' }}
      - run: echo output ${{ steps.repeater.outputs.out_var }}
        shell: bash

