name: Python CI

on:
  pull_request:
    branches: [master]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: pip install pytest
    - name: Running tests
      run: pytest exercise_2/test_bad_code.py
    # Add step to install dependencies

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: pip install black flake8
    - name: Running black
      run: black --check exercise_2/
    - name: Running flake8
      run: flake8 exercise_2/

  badging:
    runs-on: ubuntu-latest
    if: ${{ needs.lint.result == 'success' &&  needs.test.result == 'success' }}
    needs: [lint, test]
    steps:
      - uses: wow-actions/add-badges@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          badges: |
            [
              {
                "badge": "https://img.shields.io/badge/tests-passing-green",
                "alt": "test"
              }
            ]